### ISSUE TITLE
Slow Startup/Require

### ISSUE THREAD

**Issue by coreyward** [peterc/pismo#12]
I've been benchmarking the require time for the libraries in an application I'm working on to reduce the startup time (which is over 30 seconds). It turns out Pismo, which we use only rarely, takes over 1.2 seconds on my relatively speedy 13" Macbook Air. 

Here's a perftools.rb output of where that time is spent (running the following script):

```
require 'rubygems'
require 'pismo'
```

![Perftools Output](http://f.cl.ly/items/1S1s0e3E3j3T3b0R3A0c/pismo_profile.gif)

**Comment by peterc** [comment]
Maybe you have more information but I'm not seeing anything that's Pismo specific there. Pismo also doesn't "do" anything as such when it's loaded other than introduce its modules and classes and make a small monkey-patch to Nokogiri. Pismo does have several dependencies, however, the biggest of which is Nokogiri.

I just ran some benchmarks of my own and Pismo takes 282ms to load, but 193ms of that was for Nokogiri alone (so almost 70% of the time). There may be a rationale for autoload there, but it's deprecated so I'm unsure.

**Comment by coreyward** [comment]
Hmm, I wonder if there's something wrong with my 1.9.2-p290 Ruby build that it's so much slower. Switching back to 1.9.2-p180 with the patch to the require method yields similarly speedy times. 

Didn't realize Pismo was dependent on Nokogiri — I'm not very familiar with it, but its part of a project I started working on. Looks like there's not much to be done here. Closing!
