### ISSUE TITLE
UTF-8 Characters Replaced with ?

### ISSUE THREAD

**Issue by zackfern** [peterc/pismo#13]
Pismo outputs ? rather than the actual character.

Example site: http://googleblog.blogspot.com/2012/02/unicode-over-60-percent-of-web.html

Output:

> Computers store every piece of text using a "character encoding," which gives a number to each character. For example, the byte stands for 'a' and stands for 'b' in the ASCII encoding, which was launched in 1963. Before the web, computer systems were siloed, and there were hundreds of different encodings. Depending on the encoding, could mean any of ¡, ?, ?, ?, ', ", or parts of thousands of characters, from æ to ?. If you brought a file from one computer to another, it could come out as gobbledygook.Unicode was invented to solve that problem: to encode all human languages, from Chinese (??) to Russian (???????) to Arabic (???????), and even emoji symbols like or ; it encodes nearly 75,000 Chinese ideographs alone. In the ASCII encoding, there wasn't even enough room for all the English punctuation (like curly quotes), while Unicode has room for over a million characters. Unicode was first published in 1991, coincidentally the year the World Wide Web debuted—little did anyone realize at the time they would be so important for each other. Today, people can easily share documents on the web, no matter what their language. Every January, we look at the percentage of the webpages in our index that are in different encodings. Here's what our data looks like with the latest figures*: *Your mileage may vary: these figures may vary somewhat from what other search engines find. The graph lumps together encodings by script. We detect the encoding for each webpage; the ASCII pages just contain ASCII characters, for example. Thanks again to Erik van der Poel for collecting the data. As you can see, Unicode has experienced an 800 percent increase in "market share" since 2006. Note that we separate out ASCII (~16 percent) since it is a subset of most other encodings. When you include ASCII, nearly 80 percent of web documents are in Unicode (UTF-8). The more documents that are in Unicode, the less likely you will see mangled characters (what Japanese call mojibake) when you're surfing the web. We've long used Unicode as the internal format for all the text Google searches and process: any other encoding is first converted to Unicode. Version 6.1 just released with over 110,000 characters; soon we'll be updating to that version and to Unicode's locale data from CLDR 21 (both via ICU). The continued rise in use of Unicode makes it even easier to do the processing for the many languages that we cover. Without it, our unified index it would be nearly impossible—it'd be a bit like not being able to convert between the hundreds of currencies in the world; commerce would be, well, difficult. Thanks to Unicode, Google is able to help people find information in almost any language.

**Comment by peterc** [comment]
I'll need some info to try and replicate :-)

Which Ruby implementation and version?

Also, under what circumstances are you seeing this? e.g. which terminal, OS

You could get that sort of output by displaying on a terminal that's not set to UTF-8, for example, since (as far as I recall..) Pismo will transcode to UTF-8 regardless of your terminal settings.

**Comment by zackfern** [comment]
You know, I didn't even consider if the debugging output / Terminal I was viewing in even used UTF-8. Upon testing, the actual product I'm working on (that was debugging output) doesn't have any issues. 

Sorry to have wasted your time, and thanks for the help. :)

**Comment by peterc** [comment]
Hehe, that's fine. Character encoding is both difficult and a real headache to work with 99% of the time, hence my "please, let's all just speak English" campaign ;-)
